workspace_root: "./workspace"
allowed_commands:
  - git
  - npm
  - python
  - pip
  - pytest
model_configs:
  - name: "microsoft/DialoGPT-small"
    fallback: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    device: "auto"
    max_length: 2048
security:
  max_file_size_mb: 10
  max_request_size_mb: 5
  request_timeout_seconds: 30
planning:
  max_retries: 3
  retry_delay_seconds: 1
  max_steps_per_task: 10
logging:
  level: "INFO"
  file: "agent.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
